### ISSUE TITLE
environment tag should be normalized as a tag

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/datadog-trace-agent#232]
* [x] normalize in the agent the "env" config value + env coming from span metadata values as a Datadog tag
* [x] add to documentation that the env value will be normalized like a Datadog tag
* [x] fix current values in backend to fix UI for customers that use such tags

**Comment by LeoCavaille** [comment]
https://github.com/DataDog/datadog-trace-agent/pull/233 fixes bullet point 1

**Comment by galdor** [comment]
Fixed in #233.
