### ISSUE TITLE
Filter `LIMIT` ranges in sql query resources

### ISSUE THREAD

**Issue by MDrollette** [DataDog/datadog-trace-agent#390]
Including a `LIMIT x, y` in a query resource, for example when paging over results, can drastically increase the cardinality of traced resources. I would prefer if `LIMIT` ranges were filtered out of the query, or replaced with placeholders, by the agent. I could still set the original query on metadata if I wanted to identify the actual values when inspecting traces.

It appears that single `LIMIT x` is replaced with a `LIMIT ?` placeholder already. But a range `LIMIT x, y` is not.

**Comment by palazzem** [comment]
Thanks @MDrollette for spotting this! We'll plan some work around it to reduce the cardinality and collapse common queries. We'll keep you updated once we'll start working on it!
