### ISSUE TITLE
Add yaml config for log location

### ISSUE THREAD

**Issue by jyee** [DataDog/datadog-trace-agent#399]
## Currently
Currently the trace agent allows a yaml config for log level, but not for log location. This means that users without write access to /var/log will constantly get errors.

`seelog internal error: mkdir /var/log/datadog/: read-only file system`
Heroku users see this message thousands of times.

## Expected
Users should be able to specify a log location in the datadog.yaml, similar to the `log_file` config on the main Agent.

**Comment by palazzem** [comment]
@jyee merged! it will be available in the next Agent release.
