### ISSUE TITLE
Missing information in trace agent build

### ISSUE THREAD

**Issue by noviceamateur** [DataDog/datadog-trace-agent#415]
Dont we need to do a go get -d ./... before running make build to install trace agent for installing the dependencies in our go path ?
Also the make install needs to be run with the $GOPATH only right?

This is for mac

**Comment by buddhistpirate** [comment]
+1 Can we get the instructions updated a little bit to reference these 2 issues? Since there have not been pre-built MacOS packages for a while, more of us need to build it ourselves.

**Comment by gbbr** [comment]
Apologies, for some reason I assumed this would be obvious enough given the instructions in the README file [Development section](https://github.com/DataDog/datadog-trace-agent#development). It goes as follows:
```
go get -u github.com/DataDog/datadog-trace-agent/...
cd $GOPATH/src/github.com/DataDog/datadog-trace-agent
make install
```
This should do the trick. Can you confirm that this works for you? I could add the exact same snippet from above into the README if you think that would be better.

**Comment by buddhistpirate** [comment]
I think it would be a good idea to include those instructions. While those are obvious instructions for a go developer, I assume many of your users aren't go developers. Thanks!

**Comment by gbbr** [comment]
@buddhistpirate you're right, added in #426.
