### ISSUE TITLE
proposal: contrib/google.golang.org/grpc: add streaming grpc interceptor

### ISSUE THREAD

**Issue by mbyio** [DataDog/datadog-trace-agent#454]
It seems odd that only the unary interceptor was implemented instead of unary and streaming. Also, the GRPC team is considering only having streaming interceptors (since unary is actually just a special case of streaming). So it might end up being the only one you need anyway.

**Comment by gbbr** [comment]
Thanks for the suggestion, it completely makes sense. However, I'm going to close the issue since I think you've meant to open it on the [dd-trace-go](https://github.com/DataDog/dd-trace-go) repository.

**Comment by mbyio** [comment]
Whoops, that's correct, thanks.
