### ISSUE TITLE
cmd/trace-agent: resource replace rules get applied to "sql.query" tag too

### ISSUE THREAD

**Issue by mbyio** [DataDog/datadog-trace-agent#462]
Moved from https://github.com/DataDog/dd-trace-go/issues/274.

I work on a service that has to use complicated and varying WHERE expressions in its queries. There is no way to avoid this because, among other reasons, we have to use IN expressions with a varying number of arguments, and we can not convert the IN expressions into JOINs for performance reasons. This makes the Datadog APM UI harder to use because it results in a very high cardinality of resource names. The docs also indicate there is a hard limit to the allowed cardinality of a resource, and we don't want to lose data.

There are some things you could do automatically to try and group queries. But I think it might be better if you just let users customize it as an option, since there isn't really a way to cover every use case for every database. So, can you provide a hook so we can set our own function that normalizes resource names in queries? (And maybe you could provide a few examples that people can use if it fits their use case.)

Eg. I'd like to be able to write a function that automatically turns a query like this:

```
SELECT col1, col2, col3
FROM tablea JOIN tableb on tablea.col52 = tableb.col3
WHERE (tablea.col5 in (?, ?, ?, ?) AND tableb.col4 in (?, ?)) AND tablea.col76 = 5 AND tableb.col33 in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```
into a query like `SELECT col1, col2, col3 FROM tablea JOIN tableb ON tablea.col52 = tableb.col3` using a regular expression. Then the original query could be added as a tag so it can still be viewed for debugging.

**Comment by gbbr** [comment]
Thanks a lot for taking the time to move the issue here.

**Comment by gbbr** [comment]
@mbyio would you be able to use our set of replace rules to do this? You could target the resource and use a regexp to make replacements. An example is available [here](https://github.com/DataDog/datadog-trace-agent/blob/master/datadog.example.yaml#L61-L73).

**Comment by mbyio** [comment]
I'll see if we can try it out this week, thanks.

**Comment by gbbr** [comment]
In that case I guess we can consider this issue closed, right? To add back any extra information, you could use tags - wouldn't that work?

**Comment by mbyio** [comment]
Sure, we get the tags from the Go tracing integration. Should we make a separate feature request for adding that feature?

**Comment by gbbr** [comment]
I think it should be possible to accomplish what you want without making changes to the code. But I'll need your help to better understand what you're trying to do.

Can you please let me know what integration you are using, what tags and resource name you are getting and what you are expecting to see but aren't?

**Comment by mbyio** [comment]
Sure! We are using https://github.com/DataDog/dd-trace-go. To get SQL database tracing, we are using the sqlx integration. We are using the replace rules feature that you described here to cleanup the SQL queries. Since the sqlx integration uses the SQL queries as resource names, we are using the replace rules feature to cleanup the resource names.

Using the replace rules feature somewhat solves the problem of SQL queries not being grouped together, so now we can get some useful data by query. But because the resource name is being modified, we can no longer see the original query associated with a span, and we need that information to help diagnose performance problems.

**Comment by gbbr** [comment]
Even though the resource name is modified, are you not getting the `sql.query` tag set with the full query? Isn't that what you are after? Sorry if I'm not completely understanding the issue.

**Comment by gbbr** [comment]
You should definitely be getting that tag. If not, let's look into it. And yes, upgrading will most likely help (at least to a >1.0 version if you haven't already). We haven't encountered any problems with missing tags for the `jmoiron/sqlx` integration yet, and the unit tests confirm it. The only potential problem I can think of is perhaps the replace rules which might be removing them? You could maybe paste those here so we can take a look, if you also think that there is a possibility for it to be so. Otherwise, I'll wait for your update.

**Comment by mbyio** [comment]
We were already > 1.0; we upgraded today, and now we don't seem to have the `sql.query` tag, and the replace rules stopped working too. :disappointed: I will reach out via datadog support tomorrow so you, or whoever works on it, can see the actual data coming in.

**Comment by gbbr** [comment]
Sorry to hear that. We and other customers are also using these features and integrations, so I'm sure it's just a matter of settings this up correctly. I'm happy to help further via the support channel.

Let's close this issue for now, as it fixes your cardinality issue. We can keep track of this via support then. Thanks for being patient.

**Comment by gbbr** [comment]
This is a bug, we are addressing it in https://github.com/DataDog/datadog-trace-agent/pull/477. Hoping to release it as part of 6.6.0 mid-October. Thanks for working with us to pin the problem down. This is indeed an unfortunate oversight.

**Comment by mbyio** [comment]
Thanks!
