### ISSUE TITLE
Traces whose names contain no alphabetic characters are dropped

### ISSUE THREAD

**Issue by aesy** [DataDog/datadog-trace-agent#510]
I noticed a few dropped traces in the agent logs that looked like this:
`[ TRACE ] 2018-10-31 11:36:15 ERROR (api.go:249) - dropping trace reason: invalid span (SpanID:<removed> span.normalize: invalid 'Name': / (debug for more info)`
We're using [java-jaxrs](https://github.com/opentracing-contrib/java-jaxrs) to trace requests, and it sets the path as operation name, so when a request is towards the root path, such as in this case, the name is `/`. 

The relevant piece of code:
https://github.com/DataDog/datadog-trace-agent/blob/5c6958a102824d7bf8ce76e38fe43099adcf3d9b/model/normalizer.go#L195-L202

As far as I know, there's nothing in the opentracing specification specifically saying that the name must contain alphabetic characters, but I suppose it could be argued that its not 'human-readable'.

This isn't a huge issue, I could just manually give it another operation name, but then it wouldn't be consistent with the rest of the request names.

What are your thoughts?

**Comment by gbbr** [comment]
Hi @aesy!

This is a very valid question and has been a long source of confusion in our APM product. While it is true that most tracing systems out there use a path for operation name, for Datadog it is different. In Datadog, the path of the operation is what we call "resource" and the operation name is similar (but not the same) to what is called "component". Some examples of good operation names: "http.request", "sql.query", etc.

While this may seem odd at first, it allows our product to have a unique set of capabilities provided through features such as Trace Search and percentile statistics. To most effectively benefit of these features it is recommended that the root span of a trace maintains the same name throughout requests.

This document illustrates a bit what best practices are but doesn't entirely cover the topic: https://docs.datadoghq.com/tracing/visualization/.

I hope this helps a bit. Happy to provide more insights if needed. Our (awesome) support team is also glad to help teach you more about these concepts and what best practices are.

**Comment by gbbr** [comment]
Here is another article that could help: 
https://help.datadoghq.com/hc/en-us/articles/115000702546-What-is-the-Difference-Between-Type-Service-Resource-and-Name-

**Comment by aesy** [comment]
Hi @gbbr,

Thanks a lot for the reply! I see I've misunderstood how datadog treats operation names. This seems to have caused other issues for me before without me realizing it. I went ahead and mapped the operation names of the root request span to 'http.request' and everything now work as expected.

I'm closing this as this no longer is an issue.
