### ISSUE TITLE
Question asked in the #apm room

### ISSUE THREAD

**Issue by thomas91310** [DataDog/datadog-trace-agent#562]
I know this question is not meant to be asked here but I think people that work on this project can answer this question. It was also asked in the `#APM` datadog public slack room:

*thomas91310 [4:07 PM]*

hello! Let’s say, I `span.SetTag("fruit", "apple")` and on another request I `span.SetTag("fruit", "orange")`. Now let’s say I want to build a custom graph in a dashboard that shows % of requests when the fruit passed was an `apple` (similarly I also want to graph the % of requests where fruit was an `orange`)
My understanding is that it’s easy to graph `trace.spanName.hits` (which include all `apple` and `orange` requests) but that you currently can’t graph things like `trace.spanName.hits` **by** `fruit=apple` or `fruit=orange`?
I know it’s easy to do that using a statsd client but don’t want to miss something straightforward in case I can do that strictly using APM

Thanks!

**Comment by gbbr** [comment]
This seems more like a product question. I don't think this is the right place to ask. Slack was a good thought, but contacting our support team is the best option. I'm sure they are happy to give you a satisfying response.

I am closing it for now but if you don't hear back feel free to reply.
